services:
  db:
    image: postgres:15
    container_name: uv_reality_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Team#TA022 # Tell your team to use this
      POSTGRES_DB: uv_reality
    ports:
      - "5432:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d # This is the magic part
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: